#!/usr/bin/env node
/*
 * Feeds the published videos back into the docs and the roadmap.
 *
 *   node sync-docs.mjs          # scan the releases, write the data file + index
 *   node sync-docs.mjs --check  # report what would change, write nothing
 *
 * Source of truth is the release folders: any `youtube.json` carrying a
 * `result.videoId` is a published take. From those it writes:
 *
 *   docs/data/videos.json    keyed by take number — read by the `video` shortcode
 *   docs/content/videos.md   the generated series index
 *   demo/ROADMAP.md          the Status cell of each published row
 *
 * It does NOT touch the prose pages: where a video belongs inside an explanation
 * is an editorial decision, so it prints the `{{< video "003" >}}` line to paste
 * and the page each take's `doc:` key points at. Paste it once, and every later
 * re-sync keeps it current on its own.
 *
 * `publish.mjs` calls this after a successful upload, so the docs are never
 * behind the channel.
 */
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { execFile } from "node:child_process";
import { homedir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";

import { loadScenario } from "./lib/scenario.mjs";

const run = promisify(execFile);
const here = dirname(fileURLToPath(import.meta.url));
const repo = resolve(here, "..");
const RELEASES = join(homedir(), "fileclass-demos", "releases");
const DATA_FILE = join(repo, "docs", "data", "videos.json");
const INDEX_FILE = join(repo, "docs", "content", "videos.md");
const ROADMAP = join(here, "ROADMAP.md");
const GENERATED = "<!-- generated by demo/sync-docs.mjs — edits here are overwritten -->";

const dim = (s) => `\x1b[2m${s}\x1b[0m`;

/** Duration of the released video, in seconds (ffprobe, else the take's length). */
async function duration(releaseDir, meta) {
	const video = meta.files?.video ?? join(releaseDir, "video.mp4");
	if (existsSync(video)) {
		try {
			const { stdout } = await run("ffprobe", [
				"-v", "error", "-show_entries", "format=duration", "-of", "csv=p=0", video,
			]);
			const secs = Number(stdout.trim());
			if (Number.isFinite(secs) && secs > 0) return Math.round(secs);
		} catch {
			/* no ffprobe, or an unreadable file — fall through */
		}
	}
	const take = meta.take && existsSync(meta.take) ? JSON.parse(readFileSync(meta.take, "utf8")) : null;
	return take?.endedAt ? Math.round(take.endedAt / 1000) : null;
}

/** Published takes, newest release per scenario, keyed by take number. */
export async function publishedVideos() {
	if (!existsSync(RELEASES)) return {};
	const videos = {};
	for (const name of readdirSync(RELEASES).sort()) {
		// Sorted ascending, so a later release for the same take overwrites an earlier one.
		const dir = join(RELEASES, name);
		const metaPath = join(dir, "youtube.json");
		if (!existsSync(metaPath)) continue;
		const meta = JSON.parse(readFileSync(metaPath, "utf8"));
		if (!meta.result?.videoId) continue;

		let scenario = null;
		try {
			scenario = loadScenario(here, meta.scenario);
		} catch {
			continue; // the scenario folder was renamed or removed
		}
		videos[scenario.id.slice(0, 3)] = {
			id: meta.result.videoId,
			url: meta.result.url,
			title: meta.title,
			subject: meta.title.replace(/^Fileclass #\d+\s*·\s*/, ""),
			scenario: scenario.id,
			doc: scenario.doc || "",
			durationSeconds: await duration(dir, meta),
			privacyStatus: meta.result.privacyStatus ?? "unknown",
		};
	}
	return videos;
}

const clock = (secs) =>
	secs == null ? "" : `${Math.floor(secs / 60)}:${String(secs % 60).padStart(2, "0")}`;

function indexPage(videos) {
	const numbers = Object.keys(videos).sort();
	const lines = [
		"---",
		'title: "Videos"',
		'description: "One short video per feature — the whole Fileclass series."',
		"weight: 15",
		"---",
		"",
		GENERATED,
		"",
		"One feature per video, a minute or two each, in the order they build on each",
		"other. Captions are English; YouTube translates them into your language.",
		"",
	];
	for (const n of numbers) {
		const v = videos[n];
		lines.push(`## ${v.subject}`, "", `{{< video "${n}" >}}`, "");
	}
	if (!numbers.length) lines.push("_Nothing published yet._", "");
	return lines.join("\n");
}

/** Rewrites the Status cell of every published row in the roadmap table. */
function roadmapWithStatus(text, videos) {
	return text
		.split("\n")
		.map((line) => {
			const m = line.match(/^\|\s*(\d{3})\s*\|/);
			if (!m) return line;
			const v = videos[m[1]];
			if (!v) return line;
			const cells = line.split("|");
			// [0]="" [1]=number … [last]="" — the Status cell is the one before the tail.
			cells[cells.length - 2] = ` ✅ [published](${v.url}) `;
			return cells.join("|");
		})
		.join("\n");
}

/**
 * Writes the data file, the index page and the roadmap statuses.
 * @returns { videos, written, todo } — `todo` lists the shortcodes a human still
 *          has to paste into the prose pages.
 */
export async function syncDocs({ check = false } = {}) {
	const videos = await publishedVideos();
	const numbers = Object.keys(videos).sort();

	const data = `${JSON.stringify(videos, null, 2)}\n`;
	const index = indexPage(videos);
	const roadmap = roadmapWithStatus(readFileSync(ROADMAP, "utf8"), videos);
	const writes = [
		[DATA_FILE, data],
		[INDEX_FILE, index],
		[ROADMAP, roadmap],
	].filter(([path, content]) => !existsSync(path) || readFileSync(path, "utf8") !== content);

	if (!check) {
		for (const [path, content] of writes) {
			mkdirSync(dirname(path), { recursive: true });
			writeFileSync(path, content);
		}
	}

	// Where a human still has to act: the shortcode inside the prose.
	const placements = numbers
		.map((n) => ({ n, v: videos[n] }))
		.filter(({ v }) => v.doc)
		.map(({ n, v }) => {
			const page = v.doc.replace(/#.*$/, "").replace(/\/$/, "") || "_index";
			const anchor = v.doc.includes("#") ? v.doc.replace(/^.*#/, "#") : "";
			const file = join("docs", "content", `${page}.md`);
			const placed =
				existsSync(join(repo, file)) &&
				readFileSync(join(repo, file), "utf8").includes(`{{< video "${n}"`);
			return { n, file, anchor, placed };
		});

	return {
		videos,
		written: writes.map(([path]) => path),
		todo: placements.filter((p) => !p.placed),
	};
}

async function main() {
	const check = process.argv.includes("--check");
	const { videos, written, todo } = await syncDocs({ check });
	const numbers = Object.keys(videos).sort();

	console.log(`${numbers.length} published take${numbers.length === 1 ? "" : "s"}`);
	for (const n of numbers) {
		const v = videos[n];
		console.log(
			`  ${n}  ${clock(v.durationSeconds).padStart(5)}  ${v.privacyStatus.padEnd(8)} ${v.subject}`
		);
	}

	if (!written.length) console.log(dim("\nDocs already up to date."));
	else console.log(dim(`\n${check ? "Would update" : "Wrote"}:\n${written.map((p) => `  ${p}`).join("\n")}`));

	if (todo.length) {
		console.log("\nStill to place by hand, once each:");
		for (const p of todo) {
			console.log(`  {{< video "${p.n}" >}}  →  ${p.file}${p.anchor ? ` near ${p.anchor}` : ""}`);
		}
	} else if (numbers.length) {
		console.log(dim("\nEvery published take is referenced from its doc page."));
	}
}

// Only run the CLI when invoked directly — publish.mjs imports syncDocs().
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
	main().catch((err) => {
		console.error(`\n${err?.message || err}\n`);
		process.exit(1);
	});
}
